#!python

env = SConscript("../SRC/SConscript")

sources = env.Glob("src/*.c")
sources += env.Glob("${BSP_PATH}/StdPeriphDriver/*.c")
sources += ["${BSP_PATH}/Startup/startup_CH583.S"]

out = env.Program("lolicats.elf", sources)
env.Objcopy(out)
